language: csharp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: "xcode8.3"

solution: FSharp.Data.FlatFileMeta.sln

dotnet: 2.0.0

install:
  - cd Tests
  - dotnet restore

script:
  - dotnet build